{% set name = "ariadne-codegen" %}
{% set version = "0.13.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ariadne_codegen-{{ version }}.tar.gz
  sha256: 52aa67037dcd88a2f6013118e69ba0ed35a49f37312668a1969907f0e9c9bf8b

build:
  entry_points:
    - ariadne-codegen = ariadne_codegen.main:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - hatchling
    - pip
  run:
    - python >=3.7
    - click >=8.1,<9.dev0
    - graphql-core >=3.2.0,<3.3
    - toml >=0.10,<1.dev0
    - httpx >=0.23,<1.dev0
    - pydantic >=2.0.0,<3.0.0
    - black
    - isort
    - autoflake

test:
  imports:
    - ariadne_codegen
  commands:
    - pip check
    - ariadne-codegen --help
  requires:
    - pip

about:
  home: https://github.com/mirumee/ariadne-codegen
  summary: Generate fully typed GraphQL client from schema, queries and mutations!
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ytausch
